name: Upgrade all Terraform Providers

on: 
  workflow_dispatch:

jobs:
  tf-init-upgrade:
    name: Upgrade
    runs-on: [self-hosted, x64, linux, ephemeral, zon-image-latest]

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Vault OIDC Auth
        uses: hashicorp/vault-action@v2
        id: vault
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: jwt
          path: github-actions
          role: terraform-ops
          exportToken: true
          secrets: zon/v1/github/atlantis gh_token

      - name: Write gitconfig
        run: git config --global url."https://oauth2:${{ steps.vault.outputs.gh_token }}@github.com".insteadOf ssh://git@github.com # replace ssh auth with https token auth for private terraform-module repo

      - name: GCloud OIDC Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: gha-terraform@zeitonline-engineering.iam.gserviceaccount.com

      - name: Upgrade all Providers
        shell: bash
        run: |
          tfupdate terraform -r -v "1.3.2" ./

          tfupdate provider -r google -v "4.41.0" ./
          tfupdate provider -r google-beta -v "4.41.0" ./
          tfupdate provider -r kubernetes ./
          tfupdate provider -r random ./
          tfupdate provider -r "time" -v "0.9.0" ./
          tfupdate provider -r tls ./
          tfupdate provider -r vault ./
          tfupdate provider -r helm ./
          tfupdate provider -r github -v "5.7.0" ./

          tfupdate provider -r elasticsearch -v "2.0.0" ./
          tfupdate provider -r ec -v "0.9.0" ./
          tfupdate provider -r flux -v "0.20.0" ./
          tfupdate provider -r ns1 -v "1.12.8" ./
          tfupdate provider -r fastly -v "2.4.0" ./

      - name: Lock providers
        shell: bash
        run: |
          for DIR in $(find . -name '.terraform.lock.hcl' -exec dirname {} \;); do
            echo "DIR: $DIR"
            terraform -chdir=$DIR init -upgrade
            terraform -chdir=$DIR providers lock -platform=darwin_amd64 -platform=linux_amd64 -platform=darwin_arm64
          done

      - name: Push changes to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: chore-update-providers
          create_branch: true
          commit_message: "chore: Update TF Provider Lock"
          file_pattern: "**/.terraform.lock.hcl **/*.tf"
