name: Repository version
on:
  workflow_call:
    outputs:
      describe:
        description: "Output of `git describe`"
        value: ${{ jobs.describe.outputs.describe }}
jobs:
  describe:
    name: Describe version
    runs-on: zon-ubuntu-general-dind
    permissions:
      id-token: write
      contents: read
    outputs:
      describe: ${{ steps.ghd.outputs.describe }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git describe
        id: ghd
        run: echo "describe=$( git describe --tags )" >> $GITHUB_OUTPUT
