name: K8s validation
on:
  workflow_call:
    inputs:
      environments:
        description: "space-separated list of environments to validate (e.g. 'staging production')"
        default: "staging production"
        required: false
        type: string
jobs:
  validate:
    name: Validate manifests
    runs-on: zon-ubuntu-general-dind
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
    - name: Set up kubectl
      uses: azure/setup-kubectl@829323503d1be3d00ca8346e5391ca0b07a9ab0d # v5
    - name: Generate manifests
      run: |
        mkdir manifests
        for env in ${{ inputs.environments }}; do
          kubectl kustomize k8s/$env > manifests/$env.yaml
        done
    - name: Validate manifests
      uses: instrumenta/kubeval-action@5915e4adba5adccac07cb156b82e54c3fed74921 # master
      with:
        files: manifests
