name: Check code issues
on:
  workflow_call:
    inputs:
      node-version:
        description: "Optionally install Node.js with the given version"
        type: string
      setup-command:
        description: "Optional command to set up tools, plugins etc"
        type: string
        default: "uv sync --frozen --only-group lint"
      baseproject-name:
        description: "Optional project name to pass to gh-action-baseproject"
        type: string
      baseproject-environment:
        description: "Optional environment to pass to gh-action-baseproject"
        type: string
        default: "devel"
jobs:
  linter:
    name: Lefthook
    runs-on: zon-ubuntu-general-dind
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Install `uv`
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          activate-environment: true
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        if: inputs.node-version
        with:
          node-version: ${{inputs.node-version}}
      - name: baseproject
        uses: ZeitOnline/gh-action-baseproject@v0
        if: inputs.baseproject-name
        with:
          project_name: ${{inputs.baseproject-name}}
          environment: ${{inputs.baseproject-environment}}
          google_auth: true # for pypi-zon download
      - name: Run setup command
        run: ${{ inputs.setup-command }}
      - name: Run code checks
        run: lefthook run pre-commit --all-files
