name: Check code issues
on:
  workflow_call:
    inputs:
      node-version:
        description: "Optionally install Node.js with the given version"
        type: string
      setup-command:
        description: "Optional command to set up tools, plugins etc"
        type: string
        default: "uv sync --frozen --only-group lint"
jobs:
  linter:
    name: Lefthook
    runs-on: zon-ubuntu-general-dind
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Install `uv`
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          activate-environment: true
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        if: inputs.node-version
        with:
          node-version: ${{inputs.node-version}}
      - name: Run setup command
        run: ${{ inputs.setup-command }}
      - name: Run code checks
        run: lefthook run pre-commit --all-files
