name: Test code issues
on:
  workflow_call:
jobs:
  precommit:
    name: Pre-Commit
    runs-on: zon-ubuntu-general-dind
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run code checks
        run: pre-commit run --all-files
