name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
concurrency:
  group: release
  cancel-in-progress: true
jobs:
  release-please:
    name: Release please
    runs-on: zon-ubuntu-general-dind
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release please
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
